### ISSUE TITLE
Core Integration Tracker

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Altis#12]
**CURRENT**

---

**PLANNED**
- [x] Base deployment system.
- [x] Player reinforcement system.
- [ ] Selling Items.
- [ ] Selling Vehicles.
- [ ] Buying Items.
- [ ] Buying Vehicles.
- [ ] Player log-out persistence.
- [ ] Equipment persistence.
- [ ] Base persistence
- [ ] Bank persistence.
- [ ] Faction gear scripting.
- [ ] Military sector control system.
- [ ] Box labels.
- [ ] Vehicle field repair.
- [x] Magazine repack.
- [x] Custom medical.
- [ ] Training area.
- [x] Rank system
- [x] Player database.

**Comment by DEL-J** [comment]
Military AI Attacks on players should be added here somewhere.
