### ISSUE TITLE
First Deploy Tracker

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Altis#20]
### FIRST DEPLOY
- [x] Players are disabled, hidden, and black-screened at spawn origin.
- [x] Give players a relevant on-screen message and\or animated indicator if possible.
- [x] Determine map size.
- [x] Divide map into 8 edge coordinates.
- [x] Select randomly between the coordinates.
- [x] Do a findSafePos analysis on the selected position.
- [x] React according to terrain type:
- [x] If the origin point is on land: Deploy a camp.
- [x] If the origin point is on Sea: Deploy a series of boats with players as cargo.
- [x] Ranking players will be in boat crew positions (driver, gunner, commander).
- [x] Enlisted players will be in boat cargo positions.
- [x] Boat will be filled with preliminary equipment in case landing area is hot.
