### ISSUE TITLE
ALC Phase 2 - General Tracker

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Altis#24]
**Base Deployment**
- [x] Select a base to deploy via the communications menu.
- [x] Only certain ranks can deploy certain bases.
- [x] Bases should have marker on each base.
- [x] Bases of higher tier should hide markers of lower tier nearby.
- [x] Cargo container should be deployed empty. All supplies must be delivered.
- [x] Bases deployed with LARs functions.

**Player State Handling**
- [x] Add a state index to the existing player database.
- [x] State will be stored as a string.
- [x] String will be the marker name of the base the player logged out near.
- [x] Otherwise string will be nil.
- [x] All players are delivered by the logistics helicopter to the MOB.
- [x] Helicopter (Huron or Blackfish) spawns at (**findSafePos**) deployment zone, and flies to landing area.
